using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StyliSH.Generators;

[Generator]
public sealed class MonadAliasGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "StyliSH.Abstractions.Monads.Aliases.MonadAliasAttribute",
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax rds &&
                    rds.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword),
                transform: static (ctx, ct) => ExtractModel(ctx, ct))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, static (spc, model) => Generate(spc, model!));
    }

    private static MonadAliasModel? ExtractModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol structSymbol) return null;

        var syntaxNode = (RecordDeclarationSyntax)ctx.TargetNode;

        // Validation: must be partial (TODO: report STYL001 diagnostic)
        bool isPartial = false;
        foreach (var modifier in syntaxNode.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword)) { isPartial = true; break; }
        }
        if (!isPartial) return null;

        // Validation: exactly one type parameter (TODO: report STYL002 diagnostic)
        if (structSymbol.TypeParameters.Length != 1) return null;

        // Extract inner marker type from attribute argument
        var attribute = ctx.Attributes[0];
        if (attribute.ConstructorArguments.Length == 0) return null;
        var typeArg = attribute.ConstructorArguments[0];
        if (typeArg.Kind != TypedConstantKind.Type || typeArg.Value is not ITypeSymbol innerMarkerType) return null;

        // TODO: report STYL003 if inner marker doesn't implement IMonadMarker<>

        var namespaceName = structSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        var structName = structSymbol.Name;
        var typeParamName = structSymbol.TypeParameters[0].Name;
        var markerName = structName + "Marker";
        var accessibility = structSymbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
        var innerMarkerFullName = innerMarkerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new MonadAliasModel(
            namespaceName,
            structName,
            typeParamName,
            innerMarkerFullName,
            markerName,
            accessibility
        );
    }

    private static void Generate(SourceProductionContext spc, MonadAliasModel model)
    {
        spc.AddSource($"{model.StructName}.MonadAlias.g.cs", GenerateStructSource(model));
        spc.AddSource($"{model.MarkerName}.MonadAlias.g.cs", GenerateMarkerSource(model));
    }

    private static string GenerateStructSource(MonadAliasModel m)
    {
        var markerFullName = $"global::{m.Namespace}.{m.MarkerName}";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {m.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"{m.Accessibility} readonly partial record struct {m.StructName}<{m.TypeParameterName}>");
        sb.AppendLine($"    : global::StyliSH.Abstractions.Monads.IMonad<{markerFullName}, {m.TypeParameterName}>,");
        sb.AppendLine($"      global::StyliSH.Abstractions.Monads.IMonadUnwrapper<{m.StructName}<{m.TypeParameterName}>, {markerFullName}, {m.TypeParameterName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public required global::StyliSH.Abstractions.Monads.IMonad<{m.InnerMarkerFullName}, {m.TypeParameterName}> Inner {{ get; init; }}");
        sb.AppendLine();
        sb.AppendLine($"    public global::StyliSH.Abstractions.Monads.IMonad<{markerFullName}, TNewValue> RawMap<TNewValue>(");
        sb.AppendLine($"        global::System.Func<{m.TypeParameterName}, TNewValue> map)");
        sb.AppendLine($"        => new {m.StructName}<TNewValue> {{ Inner = Inner.RawMap(map) }};");
        sb.AppendLine();
        sb.AppendLine($"    public global::StyliSH.Abstractions.Monads.IMonad<{markerFullName}, TNewValue> RawBind<TNewValue>(");
        sb.AppendLine($"        global::System.Func<{m.TypeParameterName}, global::StyliSH.Abstractions.Monads.IMonad<{markerFullName}, TNewValue>> bind)");
        sb.AppendLine($"        => new {m.StructName}<TNewValue>");
        sb.AppendLine("        {");
        sb.AppendLine("            Inner = Inner.RawBind(value =>");
        sb.AppendLine($"                (({m.StructName}<TNewValue>)bind(value)).Inner)");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"    public static implicit operator {m.StructName}<{m.TypeParameterName}>(");
        sb.AppendLine($"        global::StyliSH.Abstractions.Monads.MonadWrapper<{markerFullName}, {m.TypeParameterName}> monad)");
        sb.AppendLine($"        => global::StyliSH.Abstractions.Monads.IMonadUnwrapper<{m.StructName}<{m.TypeParameterName}>, {markerFullName}, {m.TypeParameterName}>");
        sb.AppendLine("            .CastFrom(monad);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateMarkerSource(MonadAliasModel m)
    {
        var markerFullName = $"global::{m.Namespace}.{m.MarkerName}";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {m.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"{m.Accessibility} readonly record struct {m.MarkerName}");
        sb.AppendLine($"    : global::StyliSH.Abstractions.Monads.IMonadMarker<{markerFullName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::StyliSH.Abstractions.Monads.IMonad<{markerFullName}, T> Pure<T>(T value)");
        sb.AppendLine($"        => new {m.StructName}<T> {{ Inner = {m.InnerMarkerFullName}.Pure(value) }};");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

internal sealed record MonadAliasModel(
    string Namespace,
    string StructName,
    string TypeParameterName,
    string InnerMarkerFullName,
    string MarkerName,
    string Accessibility);
